# Generated by Django 4.1.2 on 2022-10-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_user_id_protocamp_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocamp',
            name='img',
            field=models.CharField(default='https://cdn4.iconfinder.com/data/icons/video-game-items-concepts/128/magic-spell-book-open-512.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='protochar',
            name='img',
            field=models.CharField(default='https://mythologian.net/wp-content/uploads/2018/02/Metatrons-Cube-Symbol-Flower-Of-Life-Meaning-Symbolism-Story-1024x1024.jpg', max_length=500),
        ),
    ]
