# Generated by Django 4.1.2 on 2022-10-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_protocamp_img_alter_protochar_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocamp',
            old_name='description',
            new_name='info',
        ),
    ]
