# Generated by Django 4.1.2 on 2022-10-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_protochar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protochar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protochar', to=settings.AUTH_USER_MODEL),
        ),
    ]
