# Generated by Django 4.1.2 on 2022-10-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_regrequest_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocamp',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
