# Generated by Django 4.1.2 on 2022-10-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_protochar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protosheet',
            name='char',
        ),
        migrations.AddField(
            model_name='protosheet',
            name='protochar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='protosheet', to='main_app.protochar'),
        ),
        migrations.AlterField(
            model_name='protosheet',
            name='subclass_code',
            field=models.CharField(default='', max_length=3),
        ),
    ]
