# Generated by Django 4.1.2 on 2022-10-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_protocamp_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regrequest',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='main_app.protochar'),
        ),
    ]
