# Generated by Django 4.1.2 on 2022-10-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_protosheet_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main_app.protochar'),
        ),
        migrations.AlterField(
            model_name='regrequest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='main_app.protocamp'),
        ),
    ]
