# Generated by Django 4.1.2 on 2022-10-17 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_protochar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocamp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='protosheet',
            name='base_class',
            field=models.CharField(choices=[('Artificer', 'Artificer'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Fighter', 'Fighter'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Rogue', 'Rogue'), ('Sorcerer', 'Sorcer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], default='Artificer', max_length=10),
        ),
    ]
