# Generated by Django 4.1.3 on 2022-11-08 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_registry_memberlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main_app.protochar'),
        ),
    ]
